name: gru_3L256_ptbword

dataset:
    origin: ptb

    # General
    name: ptb
    tokenizer: word

    context_length: 64
    dataloader_workers: 4

model:
    # Architecture
    architecture: rnn
    cell_type: gru  # simple, gru
    hidden_size: 256
    num_layers: 3
    skip_connections: True
    transformer_like: False

    # DFA options
    use_dfa: False
    state_transition: null
    measure: null

training:
    # General
    epochs: 30
    train_batch_size: 128
    eval_batch_size: 256

    # AdamW optimizer
    learning_rate: 1e-3
    weight_decay: 1e-4
    beta1: 0.9
    beta2: 0.999

    # Scheduler
    scheduler: step
    scheduler_kwargs:
        step_size: 10
        gamma: 0.1
    warmup_ratio: 0

    # Logging
    log_interval: 100
    num_evals: 50